- name: Upgrade rpm-ostree image
  hosts: homelab
  remote_user: "{{ admin_user }}"
  become: true
  tasks:
    - name: Upgrade the rpm-ostree image
      ansible.posix.rpm_ostree_upgrade:
      register: ostree_results

    - name: Reboot into new image
      ansible.builtin.reboot:
        reboot_timeout: 2000
      when: ostree_results.changed
